Repository ArkEcosystem/python-client, pull requests merged in 2019-05, with the labels that each got.

#79 feat: add node/fees endpoint
  client/api/node.py
  tests/api/test_node.py
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#82 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#84 chore: update sdk url
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#85 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#86 chore: add itsanametoo to code owners
  CODEOWNERS
Labels: Complexity: Low, Type: Task
