Repository ArkEcosystem/python-client, pull requests merged in 2020-02, with the labels that each got.

#108 release: 1.1.0
  CHANGELOG.md
  setup.py
Labels: Complexity: Low, Type: Release

#110 feat: add methods for first and last block
  client/api/blocks.py
  tests/api/test_blocks.py
Labels: Complexity: Low, Status: Member Approved, Type: Feature

#111 chore: move bridgechain show endpoint
  client/api/bridgechains.py
  client/api/businesses.py
  tests/api/test_bridgechains.py
  tests/api/test_businesses.py
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Task
